/* tslint:disable */
/* eslint-disable */
/**
 * webkansu-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Bookmark
 */
export interface Bookmark {
    /**
     * チャプターの URL を組み立てるための文字列。`/n0123ab/1/`の `1` にあたる。
     * @type {string}
     * @memberof Bookmark
     */
    slug: string;
    /**
     * スクロール位置を表す文字列。HTML の id 属性の値などが入る。
     * @type {string}
     * @memberof Bookmark
     */
    position: string;
    /**
     * チャプターのタイトル。
     * @type {string}
     * @memberof Bookmark
     */
    title: string;
    /**
     * しおりの更新日時。
     * @type {Date}
     * @memberof Bookmark
     */
    updatedAt: Date;
}

export function BookmarkFromJSON(json: any): Bookmark {
    return BookmarkFromJSONTyped(json, false);
}

export function BookmarkFromJSONTyped(json: any, ignoreDiscriminator: boolean): Bookmark {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'slug': json['slug'],
        'position': json['position'],
        'title': json['title'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function BookmarkToJSON(value?: Bookmark | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'slug': value.slug,
        'position': value.position,
        'title': value.title,
        'updated_at': (value.updatedAt.toISOString()),
    };
}


