/* tslint:disable */
/* eslint-disable */
/**
 * webkansu-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBookmarkRequestBody
 */
export interface CreateBookmarkRequestBody {
    /**
     * チャプターの URL を組み立てるための文字列。`/n0123ab/1/`の `1` にあたる。
     * @type {string}
     * @memberof CreateBookmarkRequestBody
     */
    slug: string;
    /**
     * スクロール位置を表す文字列。HTML の id 属性の値などが入る。
     * @type {string}
     * @memberof CreateBookmarkRequestBody
     */
    position: string;
    /**
     * チャプターのタイトル。
     * @type {string}
     * @memberof CreateBookmarkRequestBody
     */
    title: string;
}

export function CreateBookmarkRequestBodyFromJSON(json: any): CreateBookmarkRequestBody {
    return CreateBookmarkRequestBodyFromJSONTyped(json, false);
}

export function CreateBookmarkRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBookmarkRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'slug': json['slug'],
        'position': json['position'],
        'title': json['title'],
    };
}

export function CreateBookmarkRequestBodyToJSON(value?: CreateBookmarkRequestBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'slug': value.slug,
        'position': value.position,
        'title': value.title,
    };
}


