/* tslint:disable */
/* eslint-disable */
/**
 * webkansu-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterUserResponseBodyData
 */
export interface RegisterUserResponseBodyData {
    /**
     * 
     * @type {number}
     * @memberof RegisterUserResponseBodyData
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserResponseBodyData
     */
    provider: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserResponseBodyData
     */
    uid: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserResponseBodyData
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserResponseBodyData
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserResponseBodyData
     */
    updatedAt: string;
}

export function RegisterUserResponseBodyDataFromJSON(json: any): RegisterUserResponseBodyData {
    return RegisterUserResponseBodyDataFromJSONTyped(json, false);
}

export function RegisterUserResponseBodyDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterUserResponseBodyData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'provider': json['provider'],
        'uid': json['uid'],
        'email': json['email'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
    };
}

export function RegisterUserResponseBodyDataToJSON(value?: RegisterUserResponseBodyData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'provider': value.provider,
        'uid': value.uid,
        'email': value.email,
        'created_at': value.createdAt,
        'updated_at': value.updatedAt,
    };
}


