/* tslint:disable */
/* eslint-disable */
/**
 * webkansu-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    NovelProvider,
    NovelProviderFromJSON,
    NovelProviderFromJSONTyped,
    NovelProviderToJSON,
} from './';

/**
 * 
 * @export
 * @interface CreateNovelRequestBody
 */
export interface CreateNovelRequestBody {
    /**
     * 小説のタイトル。
     * @type {string}
     * @memberof CreateNovelRequestBody
     */
    title: string;
    /**
     * 小説の著者名。
     * @type {string}
     * @memberof CreateNovelRequestBody
     */
    authorName: string;
    /**
     * 
     * @type {NovelProvider}
     * @memberof CreateNovelRequestBody
     */
    provider: NovelProvider;
    /**
     * `n0123ab` などのprovider のサービス内で、小説の URL を組み立てるための文字列。
     * @type {string}
     * @memberof CreateNovelRequestBody
     */
    slug: string;
}

export function CreateNovelRequestBodyFromJSON(json: any): CreateNovelRequestBody {
    return CreateNovelRequestBodyFromJSONTyped(json, false);
}

export function CreateNovelRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateNovelRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'authorName': json['author_name'],
        'provider': NovelProviderFromJSON(json['provider']),
        'slug': json['slug'],
    };
}

export function CreateNovelRequestBodyToJSON(value?: CreateNovelRequestBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'author_name': value.authorName,
        'provider': NovelProviderToJSON(value.provider),
        'slug': value.slug,
    };
}


