/* tslint:disable */
/* eslint-disable */
/**
 * webkansu-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RegisterUserResponseBodyData,
    RegisterUserResponseBodyDataFromJSON,
    RegisterUserResponseBodyDataFromJSONTyped,
    RegisterUserResponseBodyDataToJSON,
} from './';

/**
 * 
 * @export
 * @interface RegisterUserResponseBody
 */
export interface RegisterUserResponseBody {
    /**
     * 
     * @type {string}
     * @memberof RegisterUserResponseBody
     */
    status: string;
    /**
     * 
     * @type {RegisterUserResponseBodyData}
     * @memberof RegisterUserResponseBody
     */
    data: RegisterUserResponseBodyData;
}

export function RegisterUserResponseBodyFromJSON(json: any): RegisterUserResponseBody {
    return RegisterUserResponseBodyFromJSONTyped(json, false);
}

export function RegisterUserResponseBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterUserResponseBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': RegisterUserResponseBodyDataFromJSON(json['data']),
    };
}

export function RegisterUserResponseBodyToJSON(value?: RegisterUserResponseBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'data': RegisterUserResponseBodyDataToJSON(value.data),
    };
}


